version: '3.4'

services:
  friday-back:
    container_name: Friday-ai-back
    image: fridayai/friday-back:dev
    build:
      context: ./
      dockerfile: ./docker/Dockerfile-development
      target: back-end
    environment:
      - NODE_ENV=development
      - MQTT_HOST=host.docker.internal
  friday-front:
    container_name: Friday-ai-front
    image: fridayai/friday-front:dev
    build:
      context: ./
    depends_on:
      - friday-back
    environment:
      - NODE_ENV=development
      - MQTT_HOST=host.docker.internal
  broker:
    container_name: Friday-ai-broker
    image: eclipse-mosquitto:latest
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./docker/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./docker/mosquitto/data:/mosquitto/data
    environment:
      - TZ=Europe/Paris
    user: 1000:1000
