version: '3.4'

services:
  friday-back:
    build:
      dockerfile: ./docker/Dockerfile-development
      target: front-end
    user: "1000:1000"
    ports:
      - "3001:3001"
    volumes:
      # Base
      - ./package.json:/src/package.json
      - ./pnpm-workspace.yaml:/src/pnpm-workspace.yaml
      - ./pnpm-lock.yaml:/src/pnpm-lock.yaml
      - ./apps/server:/src/apps/server
      - ./packages:/src/packages
  friday-front:
    user: "1000:1000"
    ports:
      - "3000:3000"
    volumes:
      # Base
      - ./package.json:/src/package.json
      - ./pnpm-workspace.yaml:/src/pnpm-workspace.yaml
      - ./pnpm-lock.yaml:/src/pnpm-lock.yaml
      - ./apps/front:/src/apps/front
      - ./packages:/src/packages
