version: '3'

services:
  friday:
    container_name: Friday
    build:
      context: ./
      args:
        - NODE_ENV=${NODE_ENV}
    restart: always
    ports:
      - "1443:1443"
      - "1444:1444"
