version: '3'

services:
  friday:
    container_name: Friday-ai
    image: fridayai/friday:dev
    build:
      context: ./
      dockerfile: ./docker/Dockerfile-development
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - MQTT_HOST=host.docker.internal
  broker:
    container_name: Friday-ai-broker
    image: eclipse-mosquitto:latest
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./docker/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./docker/mosquitto/data:/mosquitto/data
    environment:
      - TZ=Europe/Paris
    user: 1000:1000
