version: '3'

services:
  friday:
    image: fridayai/friday:edge
    ports:
      - "1443:1443"
      - "1444:1444"
  broker:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    environment:
      - TZ=Europe/Paris
