version: '3'

services:
  friday:
    container_name: Friday-ai
    build:
      context: .
      dockerfile: ./docker/Dockerfile-${NODE_ENV:-production}
    #image: friday-ai_friday
    restart: always
    ports:
      - "1444:1444"
      - "1443:1443"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - MQTT_HOST=host.docker.internal
  broker:
    container_name: Friday-ai-broker
    image: eclipse-mosquitto:latest
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./docker/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./docker/mosquitto/data:/mosquitto/data
    environment:
      - TZ=Europe/Paris
    user: 1000:1000
  watchtower:
    container_name: Friday-ai-watchtower
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup
