# base image node ----------------------------------------
FROM node:lts-alpine as base

# System dependencies
RUN npm install -g pnpm http-server cross-env \
    && apk add --no-cache sqlite make curl

WORKDIR /src

COPY ../package.json .

CMD pnpm start:prod

# builder ------------------------------------------------
FROM base as builder

WORKDIR /usr/src

COPY ../pnpm-lock.yaml ./
COPY ../*.npmrc ./


COPY ../ ./

RUN pnpm fetch \
    && pnpm install -r  \
    && pnpm --filter "./packages/*" build \
    && pnpm build \
    && pnpm --filter "./apps/server" --prod deploy pruned-server

# Friday front -------------------------------------------
FROM base as front-end

# Add friday core
COPY --from=builder /usr/src/apps/front/dist ./apps/front/dist

COPY ../apps/front/package.json ./apps/front/

ENV NODE_ENV production

# Ping friday to check heartbeat
HEALTHCHECK --interval=10s --retries=5 \
   CMD curl --fail "http://localhost:1444" || exit 1

# Export listening port
EXPOSE 1444

# Friday back ------------------------------------------
FROM base as back-end

# Add friday core
COPY --from=builder /usr/src/apps/server/dist ./apps/server/dist
COPY --from=builder /usr/src/pruned-server/node_modules ./apps/server/node_modules

COPY ../apps/server/package.json ./apps/server/

ENV NODE_ENV production

# Ping friday to check heartbeat
HEALTHCHECK --interval=10s --retries=5 \
   CMD curl --fail "http://localhost:1443" || exit 1

# Export listening port
EXPOSE 1443
