FROM node:lts-alpine

# System dependencies
RUN apk add --no-cache sqlite make python3 gcc g++

# Add friday core
WORKDIR /src

ENV NODE_ENV development

# Ping friday to check heartbeat
HEALTHCHECK --interval=50s --retries=12 \
   CMD curl --fail "http://localhost:3001" || exit 1

# Export listening port
EXPOSE 3001 9000

CMD ["npm" ,"run", "start:development"]
