const DEVICE_TYPE_LIST = {
  ALARM: 'alarm',
  AUDIO: 'audio',
  BATTERY: 'battery',
  CAMERA: 'camera',
  CONSOLE: 'console',
  COVER: 'cover',
  ELECTRICITY_CONCUMPTION: 'electricity-concumption',
  LIGHT: 'light',
  OUTLET: 'outlet',
  SENSOR: 'sensor',
  SWITCH: 'switch',
  THERMOSTAT: 'thermostat',
  VIDEO: 'video',
  UNKNOWN: 'unknown',
};

const DEVICE_SUBTYPE_LIST = {
  ALARM: {
    STATUS: 'status',
    BINARY: 'binary',
    PRESENCE: 'presence',
  },
  AUDIO: {
    STATUS: 'status',
    PLAY: 'play',
    PAUSE: 'pause',
    NEXT: 'next',
    PREVIOUS: 'previous',
    MUTE: 'mute',
    VOLUME_PLUS: 'volume-plus',
    VOLUME_MINUS: 'volume-minus',
    VOLUME: 'integer',
    TITLE: 'string',
  },
  BATTERY: {
    INTEGER: 'integer',
  },
  CAMERA: {
    IMAGE: 'image',
  },
  CONSOLE: {
    STATUS: 'status',
    BINARY: 'binary',
    GAME_TITLE: 'string',
  },
  COVER: {
    STATUS: 'status',
  },
  ELECTRICITY_CONCUMPTION: {
    ENERGY: 'energy',
    VOLTAGE: 'voltage',
    CURRENT: 'current',
  },
  LIGHT: {
    BINARY: 'binary',
    DIMMABLE: 'dimmable',
    COLOR: 'color',
    WHITE_COLOR: 'white-color',
  },
  OUTLET: {
    BINARY: 'binary',
    ENERGY: 'energy',
    VOLTAGE: 'voltage',
  },
  SENSOR: {
    DECIMAL: 'decimal',
    INTEGER: 'integer',
    BINARY: 'binary',
    PUSH: 'push',
    PRESENCE: 'presence',
    STATUS: 'status',
    TILT_ANGLE: 'tilt-angle',
    ACCELERATION_X: 'acceleration-x',
    ACCELERATION_Y: 'acceleration-y',
    ACCELERATION_Z: 'acceleration-z',
    UNKNOWN: 'unknown',
  },
  SWITCH: {
    BINARY: 'binary',
    ENERGY: 'energy',
    VOLTAGE: 'voltage',
    CURRENT: 'current',
    DIMMER: 'dimmer',
  },
  THERMOSTAT: {
    BINARY: 'binary',
    ENERGY: 'energy',
    VOLTAGE: 'voltage',
    INSTRUCTION: 'integer',
    PROGRAM: 'program',
    TEMPERATURE: 'decimal',
    HUMIDITY: 'decimal',
    CURRENT: 'integer',
  },
  VIDEO: {
    STATUS: 'status',
    PLAY: 'play',
    PAUSE: 'pause',
    NEXT: 'next',
    PREVIOUS: 'previous',
    MUTE: 'mute',
    VOLUME_PLUS: 'volume-plus',
    VOLUME_MINUS: 'volume-minus',
    VOLUME: 'integer',
    TITLE: 'string',
  },
  UNKNOWN: {
    UNKNOWN: 'unknown',
  },
};
