name: codecov

on: [pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: mathieuandrade/test-container:latest
      
    steps:
      - uses: actions/checkout@v2
         
      - name: Install dependencies
        working-directory: ./server
        run: yarn

      - name: 'Run Mocha/Chai unit tests'
        run: npm run coverage-server:junit
        
      - name: 'Publish Unit Test Results'
        uses: EnricoMi/publish-unit-test-result-action@v1.9
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: ./server/test-results.xml

      - name: 'Upload coverage to Codecov'
        uses: codecov/codecov-action@v1.2.1
        if: always()
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          fail_ci_if_error: true
          directory: ./server/
          verbose: true
